bloom/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'bloom.views.login'),
	url(r'^register/$', 'bloom.views.register'),
    url(r'^verb_add/$', 'bloom.views.verb_add'),
    url(r'^verb_update/$', 'bloom.views.verb_update'),
    url(r'^pdf/(?P<action>[a-zA-Z]+)', 'bloom.views.pdf'),
    url(r'^save_tree/$', 'bloom.views.save_tree'),
    url(r'^save_tree1/$', 'bloom.views.save_tree1'),
    url(r'^download_tree/$', 'bloom.views.download_tree'),
     url(r'^download_tree/$', 'bloom.views.download_tree'),
    url(r'^open_tree/$', 'bloom.views.open_tree'),
    url(r'^index/(?P<action>[a-zA-Z]+)', 'bloom.views.index'),    
    url(r'^index/$', 'bloom.views.index'),
    url(r'^get_words/$', 'bloom.views.get_words'),
    url(r'^login/$', 'bloom.views.login'),
    url(r'^logout/$', 'bloom.views.logout'),
    url(r'^test/$', 'bloom.views.test'),
    url(r'^generator/$', 'bloom.views.generator'),
    url(r'^generate_sentence/$', 'bloom.views.generate_sentence'),
    url(r'^contact/$', 'bloom.views.contact'),
    url(r'^about/$', 'bloom.views.about'),
    url(r'^help/$', 'bloom.views.help'),

    #url(r'^', 'bloom.views.index',{'action':'new'}),
)

search/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'search.views.home', name='home'),
    # url(r'^blog/', include('blog.urls'))
    url(r'^$', include('bloom.urls')),
    url(r'^bloom/', include('bloom.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

bloom/models.py
from django.db import models

# Create your models here.
class Taxonomy (models.Model):
    Name = models.CharField(max_length=100)
    Description = models.CharField(max_length=500)

    def __str__(self):
        return self.Name

class Word(models.Model):
    Taxonomy = models.ForeignKey(Taxonomy)
    Word = models.CharField(max_length=300)

    def __str__(self):
        return self.Word

class RelatedWord(models.Model):
    Word = models.ForeignKey(Word)
    RelatedWord = models.CharField(max_length=300)

    def __str__(self):
        return self.RelatedWord

class Guest(models.Model):
    Name = models.CharField(max_length=100)
    Email = models.EmailField(max_length=75)
    Age = models.DecimalField(max_digits=3,decimal_places=0)
    Country = models.CharField(max_length=100)
    Date    = models.DateTimeField(auto_now=1, auto_now_add=1)

    def __str__(self):
        return self.Name

class UserAccount(models.Model):
    Name = models.CharField(max_length=100)
    Email = models.EmailField(max_length=75)
    Password = models.CharField(max_length=20)
    Date    = models.DateTimeField(auto_now=1, auto_now_add=1)
    tree = models.TextField(null=1,default='')


    def __str__(self):
        return self.Name


class UserWords(models.Model):
    UserAccount = models.ForeignKey(UserAccount)
    Word = models.ForeignKey(Word)

    def __str__(self):
        return self.UserAccount.Name,' ',self.Word.Word


class UserSavedTree(models.Model):
    UserAccount = models.ForeignKey(UserAccount)
    Tree = models.TextField()
    Date = models.DateTimeField(auto_now=1, auto_now_add=1)

    def __str__(self):
        return self.Tree

bloom/forms.py
from django import forms

class UploadFileForm(forms.Form):    
    file  = forms.FileField()
	

bloom/views.py
from __future__ import unicode_literals
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect,Http404
from bloom.models import Taxonomy,Word,Guest,UserAccount,UserSavedTree
from django.core import serializers
import json
import datetime
from django.core.exceptions import ObjectDoesNotExist
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from django.core.servers.basehttp import FileWrapper
from bloom.forms import *
import hashlib

def test(request):
    if request.method == 'POST': # If the form has been submitted...
        form = UploadFileForm(request.POST,request.FILES) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass            
            file = request.FILES['file']
            data = u'' 
            for chunk in file.chunks(): 
                try:                
                    data += chunk.decode('ascii','ignore') 
                except UnicodeDecodeError:
                    break
                
                

            #if data:
                #data = data.decode('ascii', 'xmlcharrefreplace')
				
            form = UploadFileForm()   
			 
            #if  data and data.strip().startswith('<div class="tree"') and data.strip().endswith('</div>') :
            if  data and data.strip().startswith('<div') and data.strip().endswith('</div>') :    
                return render(request,'bloom/upload.html',{'data':data.strip()}) # Redirect after POST
                        
            return render(request, 'bloom/upload.html', { 'form': form, })
    else:
        form = UploadFileForm() # An unbound form

        return render(request, 'bloom/upload.html', {
            'form': form,
        })
    
def help(request):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')

    

    return render(request,"bloom/help.html")

    

def contact(request):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')

    

    return render(request,"bloom/contact.html")


def about(request):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')

    

    return render(request,"bloom/about.html")


def index(request,action='new'):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')

    request.session['tree'] = ''
    rdata = {}
    rdata['user_name'] = request.session.get('user_name','') 
    rdata['user_id'] = request.session.get('user_id',0)
    rdata['Taxonomy'] = Taxonomy.objects.all()
    rdata['Words'] = Word.objects.select_related('Taxonomy').all()

    return render(request,"bloom/index.html",{'rdata':rdata})

def generator(request):    

    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')
    
    if request.is_ajax():
        json_tree = request.POST.get('json_tree','')        
        if(json_tree):
            request.session['json_tree'] = json_tree

        return HttpResponse(json_tree)
    
    request.session['tree'] = ''
    rdata = {}
    rdata['json_tree'] = request.session.get('json_tree','') 
    rdata['user_name'] = request.session.get('user_name','') 
    rdata['Taxonomy'] = Taxonomy.objects.all()

    return render(request,"bloom/generator/generator.html",{'rdata':rdata})


def generate_sentence(request,action='new'):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')

    request.session['tree'] = ''
    rdata = {}
    rdata['user_name'] = request.session.get('user_name','') 
    rdata['Taxonomy'] = Taxonomy.objects.all()

    return render(request,"bloom/generator/generate_sentence.html",{'rdata':rdata})

def save_tree1(request):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')

    if request.is_ajax():
        
        tree = request.POST.get('tree','')
        request.session['tree'] = tree;
            
        return HttpResponse('done')
    else:
        raise Http404

def download_tree(request):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')    
        
    tree = request.session.get('tree','')
    #tree = '<ul><li><img parent_node="1" node_counter="1" taxonomy_id="1" src="/static/bloom/images/Pencil-icon.png" style="border: 0px none; display: inline;" alt="eidt" class="edit" id="edit_wrd_idundefined"><a parent_node="0" node_counter="1" taxonomy_id="1" class="tree_node" href="#">أن يتعرف الطالب sss</a><ul><li><img parent_node="1" node_counter="1" taxonomy_id="1" src="/static/bloom/images/Pencil-icon.png" style="border: 0px none; display: inline;" alt="eidt" class="edit" id="edit_wrd_idundefined"><a parent_node="1" node_counter="1" taxonomy_id="1" class="tree_node selected" href="#">aa</a><ul><li><img parent_node="1" node_counter="1" taxonomy_id="1" src="/static/bloom/images/Pencil-icon.png" style="border: 0px none; display: inline;" alt="eidt" class="edit" id="edit_wrd_idundefined"><a parent_node="1" node_counter="2" taxonomy_id="1" class="tree_node" href="#">bb</a></li><li><img parent_node="1" node_counter="1" taxonomy_id="1" src="/static/bloom/images/Pencil-icon.png" style="border: 0px none; display: inline;" alt="eidt" class="edit" id="edit_wrd_idundefined"><a parent_node="1" node_counter="2" taxonomy_id="1" class="tree_node" href="#">ccc</a></li><li><img parent_node="1" node_counter="1" taxonomy_id="1" src="/static/bloom/images/Pencil-icon.png" style="border: 0px none; display: inline;" alt="eidt" class="edit" id="edit_wrd_idundefined"><a parent_node="1" node_counter="1" taxonomy_id="1" class="tree_node new" href="#">dd</a></li></ul></li></ul></li></ul>'
    #tree = u' '.join(tree).encode('utf-8').strip()    
    if tree :
        tree = tree.encode('ascii', 'xmlcharrefreplace')
        temp = NamedTemporaryFile()
        temp.write(tree)
        #temp.flush()
        #img_temp.close()
        #temp.seek(0)
        #im.file.save("test.txt", File(img_temp))
        #user_id = request.session.get('user_id',0) 
        #tree = UserSavedTree.objects.get(UserAccount_id__exact=user_id)  
        #return HttpResponse('Error'+str(temp.read()))
        wrapper = FileWrapper(temp)
        response = HttpResponse(wrapper, content_type='text/plain')
        response['Content-Disposition'] = 'attachment; filename=data.txt'
        response['Content-Length'] = temp.tell()
        temp.seek(0)

        return response
        
    

def save_tree(request):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')

    if request.is_ajax():
        try:
            tree = request.POST.get('tree','')
            user_id = request.session.get('user_id',0) 
            user_saved_tree = UserSavedTree()

            if tree and user_id :
                try:
                    user_saved_tree = UserSavedTree.objects.get(UserAccount_id__exact=user_id)   
                    user_saved_tree.Date = datetime.datetime.now()
                    user_saved_tree.Tree = tree

                    user_saved_tree.save()                         
                    #wrd = taxonomy.word_set.create(Word=verb);                       
                    #response_data = {}
                    #response_data['word'] = serializers.serialize('json',wrd)
                    #return HttpResponse(json.dumps(response_data),content_type="application/json")                    
                    return HttpResponse(user_saved_tree)                    
                                        
                except ObjectDoesNotExist:
                    date = datetime.datetime.now()
                    user_saved_tree = UserSavedTree.objects.create(UserAccount_id=user_id,Tree=tree,Date=date)
                    user_saved_tree.save()    

        except KeyError:
            return HttpResponse('Error') # incorrect post
        # do stuff, e.g. calculate a score
        return HttpResponse('NO')
    else:
        raise Http404

def open_tree(request):
    if not request.session.get('is_logon',0):
        return redirect('/bloom/login')

    if request.is_ajax():
        try:            
            user_id = request.session.get('user_id',0)            
            if user_id :
                try:
                    user_saved_tree = UserSavedTree.objects.get(UserAccount_id__exact=user_id)   
                    return HttpResponse(user_saved_tree)                    
                                        
                except ObjectDoesNotExist:
                  return HttpResponse('Null') # incorrect post

        except KeyError:
            return HttpResponse('Error') # incorrect post
        # do stuff, e.g. calculate a score
        return HttpResponse('Null')
    else:
        raise Http404

def logout(request):
    request.session.flush()
    return redirect('/bloom/login/')   
    


def login(request):
    msg = ''
    if request.POST.get('submit',''):
        if not (request.POST.get('email',0) and request.POST.get('password',0)) :
            msg = 'يجب ملئ جميع البيانات'
        else:
            email = request.POST.get('email','')
            password = request.POST.get('password','')     
            try:
            
                user_account = UserAccount.objects.get(Email=email,Password=password)                  
                request.session['is_logon'] = 1

                request.session['user_name'] = user_account.Name
                request.session['user_id'] = user_account.id

                return redirect('/bloom/index/new')

            except ObjectDoesNotExist:
                msg = 'الرجاء التأكد من صحة اسم المستخدم او كلمة المرور '
            
             
                

bloom/templates/bloom/about.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<title>حول الموقع</title>
<style>
#container1{
		direction:rtl;
		margin:5px auto;
		width:800px;
		border: 1px solid rgb(17, 17, 17);
		border-radius: 5px ;
	}
  #title {
    box-sizing: border-box;
    color: rgb(255, 255, 255);
    
    perspective-origin: 422.4375px 21px;
    transform-origin: 422.4375px 21px;
    background: rgb(51, 51, 51) none repeat scroll 0% 0% / auto padding-box border-box;
  
    font: normal normal normal 25px/24px klavika-web, 'Helvetica Neue', Helvetica, Arial, Geneva, sans-serif;
    margin: 0px;
    outline: rgb(255, 255, 255) none 0px;
    overflow: hidden;
    padding: 25px 15px;
	font-weight:800;
	
}/*#H2_1*/
</style>
</head>

<body>
<div id="container1">
<h2 id="title">
	 حول الموقع
</h2>
<p style="padding:15px;text-align:justify;font-size:15pt;line-height:30px;">
{% load staticfiles %}
<img src="{% static 'bloom/images/about2.jpg' %}"  style="display:none;margin:10px auto;"/>
تم انجاز هذا البرنامج التعليمي المحوسب استكمالا لدرجة الدكتوراة :
<span style="font-weight:bold;text-align:center;display:block;margin:15px auto;">
للطالب/ محمد فوزي العقاد - فلسطين
</span>
في مجال التصميم التعليمي المحوسب بتخصص تكنولوجيا المعلومات في كلية علوم الحاسوب وتقانة المعلومات بجامعه السودان للعلوم والتكنولوجيا تحت اشراف السيد :
<span style="font-weight:bold;text-align:center;display:block;margin:15px auto;">
سعادة البروفسور / اسماعيل الازهرى محمد السيد الازهري     حفظة الله ،،،

</span>
</p>
</div>
</body>
</html>

bloom/templates/bloom/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="rtl">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Gagné</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{{ STATIC_URL }}bloom/js/jquery-ui-1.10.3.custom/development-bundle/themes/base/jquery.ui.all.css" />
    <script src="{{ STATIC_URL }}bloom/js/jquery-ui-1.10.3.custom/development-bundle/jquery-1.9.1.js"></script>
    <script src="{{ STATIC_URL }}bloom/js/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js"></script>
    <link rel="stylesheet" href="{{ STATIC_URL }}bloom/js/jquery-ui-1.10.3.custom/development-bundle/demos/demos.css" />
    <script src="{{ STATIC_URL }}bloom/js/combobox.js"></script>
    <script src="{{ STATIC_URL }}bloom/js/treeNodeActions.js"></script>
    <script src="{{ STATIC_URL }}bloom/js/site.js"></script>
    <script src="{{ STATIC_URL }}bloom/js/cookies.js"></script>

    <script src="{{ STATIC_URL }}bloom/js/dialog-statistics.js"></script>
    <script src="{{ STATIC_URL }}bloom/js/dialog-upload.js"></script>
    <script src="{{ STATIC_URL }}bloom/js/dialog-form.js"></script>
    <script src="{{ STATIC_URL }}bloom/js/dialog-confirm.js"></script>
    <script src="{{ STATIC_URL }}bloom/js/dialog-interactive.js"></script>
    
    <link rel="stylesheet" href="{{ STATIC_URL }}bloom/css/site.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}bloom/css/tree.css" />
    <link rel="stylesheet" href="{{ STATIC_URL }}bloom/css/dialogs.css" />
    
</head>

<body style="direction:rtl;text-align:right; display:none;">
    {% include "bloom/header.html" %} 
    {% block content %} 

    {% endblock %}
</body>

</html>

bloom/templates/bloom/bloom.html
{% extends "base.html" %}
{% block content %}
<div style="font-style:italic;font-size:10pt;margin-bottom:15px;color:white;background-color:black;padding:5px;">total result:{{ count }}</div>
{% for post in object_list %}
<h3><a href="/blog/{{ post.id }}">{{ post.title }}</a></h3>
<div class="post-meta">
	on {{ post.date }}
</div>
<div class="post-body" style="text-align:justify;">
	{{ post.body|safe|linebreaks }}
</div>
{% endfor %}
{% endblock %}

bloom/templates/bloom/contact.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
      "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<title>اتصل بنا</title>
<style>
#container1{
		direction:rtl;
		margin:5px auto;
		width:800px;
		border: 1px solid rgb(17, 17, 17);
		border-radius: 5px ;
	}
  #title {
    box-sizing: border-box;
    color: rgb(255, 255, 255);
    
    perspective-origin: 422.4375px 21px;
    transform-origin: 422.4375px 21px;
    background: rgb(51, 51, 51) none repeat scroll 0% 0% / auto padding-box border-box;
  
    font: normal normal normal 25px/24px klavika-web, 'Helvetica Neue', Helvetica, Arial, Geneva, sans-serif;
    margin: 0px;
    outline: rgb(255, 255, 255) none 0px;
    overflow: hidden;
    padding: 25px 15px;
	font-weight:800;
	
}/*#H2_1*/
</style>
</head>

<body>
<div id="container1">
<h2 id="title">
	 اتصل بنا
</h2>
<div style="padding:15px;text-align:justify;font-size:14pt;line-height:30px;">
للاتصال بنا /
<table style="width:100%;margin:auto 0;" cellpadding="4" cellspacing="4">

<tr>
<td>مشرف البحث</td>
<td colspan="3"> سعادة البروفسور / اسماعيل الازهرى محمد السيد  الازهري</td>
</tr>

<tr>
<td>البريد الالكتروني /</td>
<td>ielazhary@hotmail.com</td>
<td>جوال /</td>
<td>00249121645664</td>
</tr>

<td colspan="4"><hr/></td>
<tr>
<td>الطالب مصمم البرنامج</td>
<td colspan="3">محمد فوزي العقاد</td>
</tr>

<tr>
<td>البريد الالكتروني /</td>
<td>fouz45@hotmail.com</td>
<td>جوال /</td>
<td>00972598882310</td>
</tr>
<tr>
<td colspan="4"><hr/></td>
</tr>
<tr>
<td colspan="4">
شكرا لزيارتكم موقعنا. نرحب برسائلكم وأسئلتكم و اقتراحاتكم. نحن نتطلع دائما إلى تعزيز التفاعل من خلال الردود على رسائلكم. لا تتردد في إرسال ما تريد عبر البريد الإلكتروني:


</td>
</tr>
<tr>
<td colspan="4" style="font-weight:bold;">
لارسال رسالة بالبريد الالكتروني اتبع التالي:
</td>
</tr>

<tr>
<td colspan="4">

<form>
<table  style="width:80%;margin:auto;border:1px solid #D1D1D1;background:#E8E8E8;" cellpadding="4" cellspacing="4">
<tr><td colspan="2"></td></tr>
<tr><td>الاسم</td><td><input type="text" name="name" style="width:350px;line-height:20px;" required="true" /></td></tr>
<tr><td>الايميل</td><td><input type="email" name="name" style="width:350px;line-height:20px;" required="true" /></td></tr>
<tr><td>العنوان</td><td><input type="text" name="name" style="width:350px;line-height:20px;" required="true" /></td></tr>
<tr><td>الرسالة</td><td>
<textarea cols="50" rows="5">

</textarea>
</td></tr>
<tr><td></td><td><input type="submit" value="ارسال" style="font-size:14pt;line-height:20px;"/></td></tr>

<tr><td colspan="2"></td></tr>

</table>
</form>

</td>
</tr>
</table>

</div>
</div>
</body>
</html>

bloom/templates/bloom/dialog-interactive.html
<style type="text/css" media="screen">
#dialog-interactive table {
    border-collapse: collapse;
    width: 100%;
    line-height: 30px;
}

#dialog-interactive th {}

#dialog-interactive table,
#dialog-interactive td,
#dialog-interactive th {
    border: 1px solid black;
    text-indent: 5px;
}

#dialog-interactive input[type="button"] {
    font-weight: 700;
    margin: 10px 5px;
    font-size: 1.3em;
}

#dialog-interactive input[type="button"][disabled] {
    color: darkgoldenrod;
    cursor: not-allowed;
}

#dialog-interactive textarea {
    margin: 5px auto;
    width: 95%;
    padding: 0;
}

.ui-dialog-titlebar-minimize {
    margin-right: 25px !important;
}

[dialog-interactive-prev] {
    *background-color: cyan;
}

[dialog-interactive-next] {
    *background-color: yellow;
}

[dialog-interactive-up] {
    *background-color: blue;
}

[dialog-interactive-down] {
    *background-color: greenyellow;
}

[data-interactive-current] {
    padding: 10px !important;
    background-color: #00AEDB !important;
    color:#fff !important;
}

[data-interactive-current] span{
    color: #fff;
}


[data-interactive-current]:before{
    content:'⇐ ';
}

#dialog-interactive-upload-target{
    width: 500px;
    height: 500px;
    padding: 5px;
    margin: 5px;
    display: block;
    border:1px solid black;

}
#dialog-interactive-upload-target img{
    max-width: 490px;
    max-height: 490px; 
    display: block; 
    margin: auto auto;
}
</style>
<div id="dialog-interactive" title="المشروع التفاعلي التعليمي ( البيان )">
    <table cellpadding="2" cellspacing="2">
        <tbody>
            <tr>
                <th width="150">الدرس:</th>
                <td id="dialog-interactive-project-name"></td>
            </tr>
            <tr>
                <th width="150">الهدف:</th>
                <td id="dialog-interactive-sentence"></td>
            </tr>
            <tr>
                <th>تصنيف الهدف:</th>
                <td id="dialog-interactive-tax"></td>
            </tr>
            <tr>
                <td colspan="2">
                    <table>
                        <thead>
                            <tr>
                                <th width="50%" align="center">الاحداث التدريسية</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td align="center">
                                    <textarea id="dialog-interactive-notes" rows="10" cols="10" onchange="dialogInteractiveNotesChange(event, this)" style="width:95%; padding:5px;"></textarea>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
            <tr>
                <td colspan="2" align="center">
                    <input type="button" id="dialog-interactive-prev" value="&#8658;" onclick="moveInteractiveNode('prev')">
                    <input type="button" id="dialog-interactive-up" value="&#8657;" onclick="moveInteractiveNode('up')">
                    <input type="button" id="dialog-interactive-down" value="&#8659;" onclick="moveInteractiveNode('down')">
                    <input type="button" id="dialog-interactive-next" value="&#8656;" onclick="moveInteractiveNode('next')">
                </td>
            </tr>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    $(function(){


        $('#dialog-interactive-upload-target').dialog({ autoOpen: false, width:520, height: 520});
        $('#dialog-interactive-image-upload').dblclick(function(){ 
            $('#imgUpload').trigger('click'); 
        });
        $('#dialog-interactive-movie-upload').dblclick(function(){ 
            $('#movieUpload').trigger('click'); 
        });
        $('#dialog-interactive-music-upload').dblclick(function(){ 
            $('#musicUpload').trigger('click'); 
        });

        function readURL(input) {

            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $('#dialog-interactive-image-upload').attr('src', e.target.result);
                    $('[data-interactive]').attr('data-image-src', e.target.result);
                }

                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#imgupload").change(function(){
            readURL(this);
        });//click


        $('#dialog-interactive-image-upload').click(function(event){
            if($('[data-interactive][data-image-src]').size() > 0){
                $image = $('<img>', {
                    src: $('[data-interactive]').attr('data-image-src')
                })
                $('#dialog-interactive-upload-target').html( $image );                
                $('#dialog-interactive-upload-target').dialog('open');

            }//end if            
        });
    });
</script>

<div id="dialog-interactive-upload-target" title="عرض">

</div>

bloom/templates/bloom/index.html
{% extends "bloom/base.html" %} {% block content %} {% csrf_token %} {% include "bloom/search-box.html" %} {% include "bloom/dialogs.html" %} {% include "bloom/dialog-interactive.html" %}
<div class="tree" id="tree">
</div>
<script type="text/javascript">
$(function() {
    $("input[type=button]").button();
});

var $editImg = $('<img>', {
    src: '{{ STATIC_URL }}bloom/images/Pencil-icon.png',
    style: 'border:0;display:none;',
    alt: 'edit',
    class: 'edit'
});

generateNewTree(null, function() {
    $('body').fadeIn('slow');
});

genertateStatistics1();
</script>
{% endblock %}

bloom/templates/bloom/upload.html

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<title></title>
<link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.4.2/pure-min.css">
<style type="text/css">
	html{
		direction: rtl;
	}
</style>
</head>

<body>
{% if form  %}

<div  style="width:400px;padding:20px;border:1px solid #DFDFDF;margin:5px;">		
		

	<form action="/bloom/test/" method="post" enctype="multipart/form-data" class="pure-form">{% csrf_token %}
		<fieldset>
	        <legend>رفع الملف</legend>
	{{ form.non_field_errors }}
	    <div class="fieldWrapper">
	        {{ form.file.errors }}
	        <label for="id_file">الملف:</label>
	        {{ form.file }}
	    </div>

	</fieldset>
	<input type="submit" value="رفع" class="pure-button pure-button-primary" style="font-size: 85%;"/>
	</form>
</div>
{% endif %}

{% if data %}	
	<script type="text/javascript">

		parentWindow = window.top;
		//parentWindow = window.parent;
		if(parentWindow)
		{
			var data = '{{data|safe}}';
			if( data &&  data.trim().slice( 0, 4 ) && data.trim().slice( -5 )  ){
				parentWindow.document.getElementById('tree').outerHTML = data;
			}
			parentWindow.genertateStatistics1();
			parentWindow.setProjectName(null,window.parent.document);	
			parentWindow.dialog_upload_close();

			
		}

	</script>
{% endif %}

</body>

</html>